# Generated by Django 4.1.1 on 2022-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('strategy', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('process', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('people', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('customers', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
